[package]
name = "urng_core"
version = "0.1.1"
edition = "2024"
rust-version = "1.86"
keywords = ["no_std", "random", "rng"]
description = "A minimal rng core library"
readme = "crates-readme.md"
authors = ["cet"]
repository = "https://github.com/cet-t/urng_core"
license = "MIT OR Apache-2.0"

[dependencies]
pastey = "0.2.3"
